CREATE TABLE CUSTOMER (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100)
);

CREATE TABLE PRODUCT (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(100),
    UNIT_PRICE NUMERIC(20,2)
);

CREATE TABLE ORDER_CUSTOMER (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INTEGER REFERENCES CUSTOMER (ID),
    DATA_ORDER TIMESTAMP,
    TOTAL NUMERIC(20,2)
);

CREATE TABLE ITEM_ORDER (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID INTEGER REFERENCES ORDER_CUSTOMER (ID),
    PRODUCT_ID INTEGER REFERENCES PRODUCT (ID),
    AMOUNT INTEGER
);